spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://gitlab.rockstargame.cn/guopc/spring-cloud-config.git
          search-paths: respo
          username: guopc
          password: 12345678
  boot:
    admin:
      client:
        url: http://localhost:8084

  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

